passiveData = {}

passiveData['dualWield'] = 'Attack twice regardless of agility';
passiveData['flameLord'] = 'Fire magic deals more damage'
passiveData['iceLord'] = 'Ice magic deals more damage'
passiveData['windLord'] = 'Wind magic deals more damage'
passiveData['thunderLord'] = 'Bolt magic deals more damage'
passiveData['seraph'] = 'Light magic deals more damage'
passiveData['demonLord'] = 'Void magic deals more damage'
passiveData['leechLord'] = 'Drain magic deals more damage'
passiveData['keenEye'] = 'increase critical hit chance'
passiveData['keenEye+'] = 'increate ciritical hit chance further'
passiveData['evasion'] = 'chance to dodge normal attack'
passiveData['evasion+'] = 'higher chance to dodge normal attack'
passiveData['strong(element)'] = 'gain strong resistance to that element'
passiveData['immune(element)'] = 'gain immunity to that element'
passiveData['arcaneProtection'] = 'gain strong resistance to fire, ice, wind and lightning'
passiveData['celestialProtection'] = 'gain strong resistance to light and void'
passiveData['regenerate'] = 'recover HP every turn'
passiveData['echoMagic'] = 'chance to cast magic twice'
passiveData['basher'] = 'chance to stun the enemy on normal attack'
passiveData['executor'] = 'chance to instantly kill enemy on normal attack'
passiveData['pincher'] = 'Normal attack steals money from the enemy'
passiveData['snatcher'] = 'Normal attack may steal item from the enemy'
passiveData['counter'] = 'Counters when hit with normal attack'
passiveData['piercer'] = 'Attack goes through armored enemies defense'
passiveData['lightWielder'] = 'Gain atk power when equipped with sword, dagger or fists'
passiveData['HeavyWielder'] = 'Gain atk power when equipped with axe, hammer or spear'
passiveData['fireCombo'] = 'Normal attack is followed by Flame I'
passiveData['iceCombo'] = 'Normal attack is followed by Ice I'
passiveData['windCombo'] = 'Normal attack is followed by Typhoon I'
passiveData['boltCombo'] = 'Normal attack is followed by Lightning I'
passiveData['manaSaver'] = 'Magic attack have a chance to return back the MP cost after casting'
passiveData['lastStand'] = 'if HP is more than 1, then killing blow will left with 1 HP'

return passiveList