passiveData = {}

passiveData['dualWield'] = 'Attack twice regardless of agility';
passiveData['flameLord'] = 'Fire magic deals more damage'
passiveData['iceLord'] = 'Ice magic deals more damage'
passiveData['windLord'] = 'Wind magic deals more damage'
passiveData['thunderLord'] = 'Bolt magic deals more damage'
passiveData['seraph'] = 'Light magic deals more damage'
passiveData['demonLord'] = 'Void magic deals more damage'
passiveData['leechLord'] = 'Drain magic deals more damage'
passiveData['keenEye'] = 'increase critical hit chance'
passiveData['keenEye+'] = 'increate ciritical hit chance further'
passiveData['evasion'] = 'chance to dodge normal attack'
passiveData['evasion+'] = 'higher chance to dodge normal attack'
passiveData['immune(element)'] = 'gain immunity to that element'
passiveData['arcaneProtection'] = 'gain strong resistance to fire, ice, wind and lightning'
passiveData['celestialProtection'] = 'gain strong resistance to light and void'
passiveData['regenerate'] = 'recover HP every turn'
passiveData['echoMagic'] = 'chance to cast magic twice'
passiveData['basher'] = 'chance to stun the enemy on normal attack'
passiveData['stabber'] = 'chance to wound the enemy on normal attack'
passiveData['breaker'] = 'chance to lower enemy defense on normal attack'
passiveData['crippler'] = 'chance to lower enemy agiliy on normal attack'
passiveData['executor'] = 'chance to instantly kill enemy on normal attack'
passiveData['pincher'] = 'Normal attack steals money from enemy'
passiveData['counter'] = 'Counters when hit with normal attack'
passiveData['lightWielder'] = 'Gain atk power when equipped with sword, dagger or fists'
passiveData['HeavyWielder'] = 'Gain atk power when equipped with axe, hammer or spear'

return passiveList